AWSTemplateFormatVersion: "2010-09-09"
Description: spin up infra for cloud9 dev env
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          Default: "VPC Configuration for Cloud9"
          Parameters:
            - VpcCidr
            - Cloud9Subnet
            - AvailabilityZone
Parameters:
  VpcCidr:
    Type: String
    Default: 10.10.0.0/22
  Cloud9Subnet:
    Type: String
    Default: 10.10.0.0/24
  AvailabilityZone:
    Type: String
    Default: us-east-1a
Resources:
  Cloud9Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: 'cloud9-vpc'
  Cloud9Igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: 'cloud9-gateway'
  Cloud9RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Cloud9Vpc
      Tags:
        - Key: Name
          Value: 'cloud9-route-table'
  AttachGatewayA:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Cloud9Vpc
      InternetGatewayId: !Ref Cloud9Igw
  Cloud9Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      VpcId: !Ref Cloud9Vpc
      CidrBlock: !Ref Cloud9Subnet
      Tags:
        - Key: Name
          Value: 'cloud9-subnet'
  Cloud9SubnetRouteTableAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Cloud9Subnet
      RouteTableId: !Ref Cloud9RouteTable
  Cloud9EIPA:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !Ref Cloud9Vpc
  Cloud9IgwRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref Cloud9RouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref Cloud9Igw
      DependsOn: !Ref Cloud9Igw